### ISSUE TITLE
Getting the output of the pr title check to use in the next step

### ISSUE THREAD

**Issue by lunaticmonk** [thehanimo/pr-title-checker#12]
Hi, here is what I am trying to do:

I want to check the regex in the PR title and when it matches, I want to check if a specific label is applied on the PR or not.

This is how my config json looks:
```json
{
  "LABEL": {
    "name": ""
  },
  "CHECKS": {
    "prefixes": ["xyz: "],
    "regexpFlags": "i",
    "ignoreLabels" : ["dont-check-PRs-with-this-label", "meta"],
    "alwaysPassCI": true
  },
  "MESSAGES": {
    "success": "y",
    "failure": "n",
    "notice": ""
  }
}
```

And this is how the github action looks:

```
name: "PR Title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  titleCheck:
    runs-on: [ self-hosted ]
    steps:
      - id: title_check
        name: check pr title for keyword
        uses: thehanimo/pr-title-checker@v1.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title.json"
  labelCheck:
    runs-on: [ self-hosted ]
    needs: [ titleCheck ]
#    this check not working
    if: needs.steps.title_check.result == 'y'
    steps:
      - name: check label
        run: echo desired pr
```

Is there a way I can access the `MESSAGES.success` in the `labelCheck` job? Please help.
