### ISSUE TITLE
I want to use conventional-changelog/commitlint for PR title check

### ISSUE THREAD

**Issue by Neeraj-swarnkar** [thehanimo/pr-title-checker#31]
Hi Team,

I am using your Action/Workflow, Thanks for the great effort,
I need your help, I want to use 
https://www.conventionalcommits.org/en/v1.0.0/#examples
conventional-changelog/commitlint for PR title check

Can we use some regex for this, or if this action support this already how to use it ?

Please guide. I am sharing my json and yml code below. Thanks.

JSON file -
```
{
	"LABEL": {
		"name": "title needs formatting",
		"color": "EEEEEE"
	},
	"CHECKS": {
		"prefixes": ["build: ", "chore: ", "ci: ", "docs: ", "feat: ", "fix: ", "perf: ", "refactor: ", "revert: ", "test: "],
		"regexp": "docs\\(v[0-9]\\): ",
		"regexpFlags": "i",
		"ignoreLabels": ["dont-check-PRs-with-this-label", "meta"]
	},
	"MESSAGES": {
		"success": "All OK",
		"failure": "Failing CI test",
		"notice": ""
	}
}
```

YML file -
```

# This workflow/action checks if PR titles conform to the Contribution Guidelines
# For more information see: https://github.com/webex/pr-title-checker

name: pr-title-checker
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main
      - dev
      - beta
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: webex/pr-title-checker@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-title-checker-config.json
```

`prefixes` in JSON is totally working fine for commits title, but there could be some other examples like fix(parser):, feat(feature-name):, breaking change, !, etc. Can we use regexp for commitlint for PR title or something.

I don't want to switch to another action, so I am asking for solution.

@thehanimo, @feychenie, @jcw-
