### ISSUE TITLE
After title error and once properly formatted, title checker doesn't re-run and pass.

### ISSUE THREAD

**Issue by davidsteelebrady** [thehanimo/pr-title-checker#7]
Hi there, 

Potentially not understanding usage properly here but to replicate. 

1. Using 
```
    name: PR Title check
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
2. Create a PR with a poorly formatted title.
3. Title checker correctly identifies issue with title.  
![image](https://user-images.githubusercontent.com/76475855/138262830-b761fc6b-aabf-4198-9b6d-fc378073baad.png)
4. Fix title to pass Regex
5. Pipeline does **NOT** automatically re-run title checker. 

Is there a way to re-run the title checker without having to add to the PR?
